---
version: '3.7'
services:
  redirector:
    image: redirector
    build: .
    ports:
      - "3000:80"
    environment:
      REDIRECT_CODE: "302"
      REDIRECT_TARGET: "https://www.zappi.io"
      IGNORE_REQUEST_URI: "true"
